### ISSUE TITLE
inject crash

### ISSUE THREAD

**Issue by HeXz69** [Lak3/ProjectIC_TF2#2]
after injecting the cheat there is an immediate crash, after doing a debug there is this error "Reported exception at location 0x42F14686 (IC.dll) in hl2.exe: 0xC0000005: Access policy violation while reading at location 0xE30BBF34." and indicates this line as the problem https://i.imgur.com/Hlxvh7d.png.I know you wrote on UC that you don't support it anymore but please help it is one of the best open source cheats along with melancholy

**Comment by Lak3** [comment]
Hey, looks like I have not noticed this issue earlier so sorry for the late reply. I suggest you to use the SEOwned source, it's not flawless but it is an improvement over this base. Link here: https://github.com/spook953/SEOwnedPublic/

Anyhow the crash happens because of changes in the Steam's client some time ago. Simplest fix would just be to change the interface grabbing code to what you see is used in the SEOwned source. But I still suggest you don't use this and use SEOwned source / base instead!
